<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LPTIN453" name="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases" tests="6" failures="1" timestamp="2020-05-20T23:40:37 IST" time="13.755" errors="0">
  <testcase name="CreatefaSAPStatus" time="2.866" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;200&gt; but was:&lt;400&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<400>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases.CreatefaSAPStatus(TC004_faSAPStatusCRUDTestCases.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CreatefaSAPStatus -->
  <testcase name="CreateCodeAlreadyExistsValidationfaSAPStatus" time="0.650" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases"/>
  <testcase name="GetEditModefaSAPStatus" time="1.133" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases"/>
  <testcase name="EditfaSAPStatus" time="7.647" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases"/>
  <testcase name="GetDeletefaSAPStatus" time="0.790" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases"/>
  <testcase name="DeletefaSAPStatus" time="0.669" classname="com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases"/>
</testsuite> <!-- com.student.Configuration.TestCases.TC004_faSAPStatusCRUDTestCases -->
